import Providers from '@/providers/providers'
import '../style/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import SideBar from '@/components/SideBar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next13 App with Zustand',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      style={{ colorScheme: 'light' }} // <--
      className="light"
    >
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <Navbar />
          <main className="container flex flex-1">
            <div className="hidden md:flex md:w-1/5">
              <SideBar />
            </div>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
